### ISSUE TITLE
Charles 4.1.2

### ISSUE THREAD

**Issue by HeIp** [100apps/charles-hacking#10]
Patched .sh hack for 4.1.x

**Comment by vob636** [comment]
#!/usr/bin/env bash
charles=/Applications/Charles.app/Contents/Java/charles.jar
dir=charleshack

mkdir $dir
cd $dir
cat >> qFep.java <<EOF
package com.xk72.charles;
public final class qFep {
	public static boolean gtOW() { return true; }
	public static String SkgP() { return "http://www.gfzj.us"; }
	public static String gtOW(String name, String key) { return null; }
}
EOF
javac -encoding UTF-8 qFep.java -d .&& jar -uvf $charles com/xk72/charles/qFep.class
cd .. && rm -rf $dir

**Comment by grandsilence** [comment]
Thank you, but already late)

**Comment by HeIp** [comment]
https://www.charlesproxy.com/assets/release/4.1.2/charles-proxy-4.1.2.dmg 
For the crack vob636 posted , since I don't know how to find the new final class name
