### ISSUE TITLE
Not working on 4.1.3

### ISSUE THREAD

**Issue by realopty** [100apps/charles-hacking#11]
This isnt working for me on 4.1.3

charles=../charles.jar
dir=charleshack

mkdir $dir
cd $dir
cat >> psPJ.java <<EOF
package com.xk72.charles;
public final class psPJ {
        public static boolean qIvM() { return true; }
        public static String tCiz() { return "http://www.gfzj.us"; }
        public static String ItXW() { return "http://www.gfzj.us"; }
        public static String qIvM(String name, String key) { return null; }
}
EOF
javac -encoding UTF-8 psPJ.java -d .&& jar -uvf $charles com/xk72/charles/psPJ.class

**Comment by HeIp** [comment]
because the java file changed, there is no public hack public for this version by the author

**Comment by danywheeler** [comment]
charles=/Applications/Charles.app/Contents/Java/charles.jar
dir=charleshack
mkdir $dir
cd $dir
cat >> psPJ.java <<EOF
package com.xk72.charles;
public final class psPJ {
    public static boolean qIvM() { return true; }
    public static String tCiz() { return "https://0x0d.im"; }
    public static String qIvM(String name, String key) { return null; }
}
EOF
javac -encoding UTF-8 psPJ.java -d .&& jar -uvf $charles com/xk72/charles/psPJ.class
cd .. && rm -rf $dir


类名改了，用这个就行了

**Comment by HeIp** [comment]
how you find the class name ? & Thank you! / 你怎么找到类名？ ＆ 谢谢！

**Comment by 100apps** [comment]
You can update to the latest version:
https://github.com/100apps/charles-hacking/tree/master/4.2
