### ISSUE TITLE
4.1.4?

### ISSUE THREAD

**Issue by mtshare** [100apps/charles-hacking#13]
Any news about it?

**Comment by charles414** [comment]
charles=/Applications/Charles.app/Contents/Java/charles.jar
dir=charleshack

mkdir $dir
cd $dir
cat >> gIbD.java <<EOF
package com.xk72.charles;
public final class gIbD {
        public static boolean xUFT() { return true; }
        public static String PcqR() { return "http://www.gfzj.us"; }
        public static String xUFT(String name, String key) { return null; }
}
EOF
javac -encoding UTF-8 gIbD.java -d .&& jar -uvf $charles com/xk72/charles/gIbD.class
cd .. && rm -rf $dir

**Comment by txtsd** [comment]
@charles414 Can you add this to the repo, please?

**Comment by randykaskuser** [comment]
its work on ubuntu 16.04 LTS
sudo cp '/home/randykaskuser/Downloads/CharlesHack-master/charles.jar' '/usr/lib/charles-proxy'

**Comment by mtshare** [comment]
Thanks ;)
