### ISSUE TITLE
Stuck on Loading Preferences (v4.1.4)

### ISSUE THREAD

**Issue by rohitkhatri** [100apps/charles-hacking#14]
After replacing the charles.jar with the one provided in this repository, It always stuck on Loading Preferences.

<img width="661" alt="screen shot 2017-07-31 at 10 07 35 pm" src="https://user-images.githubusercontent.com/12977724/28788114-b6b57500-763c-11e7-9daa-c177c17cba05.png">

**Comment by HeIp** [comment]
https://github.com/HeIp/CharlesHack get the one from here @rohitkhatri

**Comment by 100apps** [comment]
You can update to the latest version: 
https://github.com/100apps/charles-hacking/tree/master/4.2
