### ISSUE TITLE
Charles Updated to 4.2.1

### ISSUE THREAD

**Issue by HeIp** [100apps/charles-hacking#17]
Link to updated hack.sh file for Charles 4.2.1: 
https://github.com/HeIper/CharlesHack/blob/master/hack.sh

**Comment by Ray-Eldath** [comment]
@100apps

**Comment by ibnbd** [comment]
@HeIper not working at OSX

**Comment by AugusDogus** [comment]
Confirming this does not work on OSX.

**Comment by AugusDogus** [comment]
This does work in OSX. An issue you may be experiencing is that by default you are unable to modify applications. The system detects the changes you've made and my guess is that the signature has changed and the application is then no longer signed and recognized as being developed by an Apple developer. 

To get around this, go to system preferences.
<img src="https://image.prntscr.com/image/EDt8FxfFSFCdlOde1Zaf1Q.png"></img>
Then navigate to Security & Privacy.
<img src="https://image.prntscr.com/image/3QfgLlq4SBOi9Ei-wvmMhA.png"></img>
Finally enable modifications by clicking the lock in the bottom left and entering your password and select the `anywhere` radio button.

If you do not see this `anywhere` radio button, you may be on a version of OSX that by default does not display this. To solve this issue you need to disable gatekeeper and can do so by executing the command `sudo spctl --master-disable` in your console. If you want to for whatever reason in the future re-enable this feature you can do so with `sudo spctl --master-enable`. 

([source](http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/))

**Comment by bt** [comment]
@AugusDogus it seems like it's really random. After patching myself, I see that it will get stuck on `Loading Preferences`. I think it has something to do with the version of JDK that you use.

Possible for you to share your `.jar` file?

**Comment by ibnbd** [comment]
@AugusDogus @bt thanks
So, while Charles was open I ran the script and it worked from next launch.

**Comment by bt** [comment]
@ibnbd Thanks for the reply, just tried that and still getting same issue unfortunately...

https://i.imgur.com/yQf375e.png

Possible to share the `.jar` file?

**Comment by ibnbd** [comment]
@bt uninstall Charles using any uninstall which will erase all system files as well. Reinstall and open the app, while app windows is loaded, run the script file. Wait for script to finish, close Charles and open again. No need to put jar file there, that script will modify existing jar file from Charles.

Best of luck

**Comment by Penetratitor** [comment]
@bt Hey, This is probably due to permissions,

This might do the trick:
sudo chown YourUserNAME:Admin charles.jar
