### ISSUE TITLE
Update for 4.2.6

### ISSUE THREAD

**Issue by HeIp** [100apps/charles-hacking#25]
charles=/Applications/Charles.app/Contents/Java/charles.jar
dir=charleshack

mkdir $dir
cd $dir
cat >> GPSz.java <<EOF
package com.xk72.charles;
public final class GPSz {
	public static boolean SWIF() { return true; }
	public static boolean Dgmx() { return true; }
	public static String Wmmw() { return "Administrator"; }
	public static String Ifzu() { return "Administrator"; }
	public static String Dgmx(String name, String key) { return null; }
}
EOF
javac -encoding UTF-8 GPSz.java -d .&& jar -uvf $charles com/xk72/charles/GPSz.class
cd .. && rm -rf $dir

not working for me

**Comment by playniuniu** [comment]
me too

you can use try tool [https://www.zzzmode.com/mytools/charles/](https://www.zzzmode.com/mytools/charles/)

**Comment by HeIp** [comment]
@tsauzeau master cracker please help

**Comment by playniuniu** [comment]
you can use jadx to decompile the new charles.jar and check the different with the old one

I check it, and see it replace the Dgmx() and Wmmw() function, but not replace other function

Hope it help for you

**Comment by peter23** [comment]
This code works:
```
package com.xk72.charles;
public final class GPSz {
	public static boolean Dgmx() { return true; }
	public static boolean HFjb() { return true; }
	public static String AKCM() { return "Administrator"; }
	public static String Wmmw() { return "Administrator"; }
	public static String Dgmx(String name, String key) { return null; }
}
```

**Comment by HeIp** [comment]
@peter23 I get stuck on loading preferences with that one

**Comment by peter23** [comment]
@Help it works without any problem on my side.

**Comment by HeIp** [comment]
Can you supply the full file ?

**Comment by playniuniu** [comment]
@peter23 On OSX 10.13.5, Java 10.0.1 version, It hangs on loading preferences, same problem as @HeIp

**Comment by HeIp** [comment]
Fixed & Found a Solution 👍 
Check out on my Repo 🥇 
https://github.com/HeIp/CharlesHack
