### ISSUE TITLE
v4.1

### ISSUE THREAD

**Issue by WTFObstSalat** [100apps/charles-hacking#6]
hello,

the do it yourself hack doesn't work anymore for the latest version of charlesproxy
can you update it or is it now unpossible to hack it?

**Comment by HeIp** [comment]
I just tested it, works fine

**Comment by WTFObstSalat** [comment]
yes, the .jar file is working for me too but not the script hack 

the script doesnt work anymore with higher versions of charlesproxy ( for me )

**Comment by HeIp** [comment]
The 4.1.1 script , the sh file works fine

**Comment by WTFObstSalat** [comment]
Oh i didn't saw that you Updated your Code or i oberlook the last text 

I will Test it with the next Update of charles

**Comment by WTFObstSalat** [comment]
Now i only Need to rename the charles.4.1.jar to the latest Version in replace it with original .jar ? 

Or I have to run the script too ?

**Comment by ltjin** [comment]
@WTFObstSalat, the charles.4.1.jar(only v4.1) is not available for the latest version(v4.1.1).
You can run the 4.1.1 script.
